#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

hash hexdump 2>/dev/null || ( echo 'To use the "search" command-line tool you need to install a hexdump' && exit 1 )
hash hxnormalize 2>/dev/null || ( echo 'To use the "search" command-line tool you need to install a html-xml-utils' && exit 1 )
hash curl 2>/dev/null || ( echo 'To use the "search" command-line tool you need to install a curl' && exit 1 )

[ $# -lt 1 ] && ( echo "Usage: $0 [keywords]" && exit 1)

query="$(echo -ne "$@" | hexdump -v -e '/1 "%02x"' | sed 's/\(..\)/%\1/g')"
useragent="request"
header="Content-Type: application/x-www-form-urlencoded"
url="$(printf 'http://www.google.com/search?hl=&q=%s&start=0&sa=N&num=10&ie=UTF-8&oe=UTF-8' "$query")"

curl -A "$useragent" --header "$header" --location "$url" 2>/dev/null |
    hxnormalize -x -l 1000 2>/dev/null |
    hxselect -i -s '|||' '.g' |
    tr '\n' ' ' |
    sed $'s/|||/\\\n/g' |
    sed 's/  */ /g' |
    while read LINE
    do
        result="$(echo $LINE | hxnormalize -x -l 1000)"

        title="$(echo $result |
            hxselect -c h3 a |
            sed -e 's/<b>//g' -e 's|</b>||g' )"
        link="$(echo $result | hxselect -c 'cite' |
            sed 's/<\\?b>//g' |
            sed -e 's/<b>//g' -e 's|</b>||g' )"
 
        if [ -z "${NOCOLOR+x}" ]
        then
            meta="$(echo $result |
                hxselect -c .st |
                hxremove span.f |
                hxunent |
                sed -e 's/<b>/\\033[1m/g' -e 's|</b>|\\033[0m|g' )"

            echo -e "\033[34m$title\033[0m"
            echo -e "\033[32m$link\033[0m"
        else
            meta="$(echo $result |
                hxselect -c .st |
                hxremove span.f |
                hxunent |
                sed -e 's/<b>//g' -e 's|</b>||g' )"

            echo -e "$title"
            echo -e "$link"
        fi
        echo -e "$meta" | \
           fold -w 80 -s
        echo
    done

